# Application Name
spring.application.name=HealthCareManagement

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Configuration (PostgreSQL)
#spring.datasource.url=jdbc:postgresql://172.30.240.1:5432/postgres - Podman deployment
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=abisek
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.healthcare.mgnt=DEBUG
# logging.file.name=logs/healthcare-management.log

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Security (JWT example, adjust as needed)
jwt.secret=mysupersecurejwtsecretkey1234567890abcd
jwt.expiration=86400000


# Flyway Multi-Schema Configuration
spring.flyway.enabled=true
spring.flyway.schemas=sims,miot,apollo
spring.flyway.default-schema=sims
spring.flyway.locations=classpath:db/migration
spring.flyway.ignoreUnknownDatabase=true
spring.flyway.baseline-on-migrate=true
