input {
  tcp {
    port => 5000
    codec => json
  }
  file {
    path => "/logs/healthcare-management.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  # Optionally add filters here
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "healthcare-logs-%{+YYYY.MM.dd}"
  }
}

